apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: lanchonete-app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: app
          image: juclops/techchallenge-app:v1.1.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-env
            - secretRef:
                name: app-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
              ephemeral-storage: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always