apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: lanchonete-app
type: Opaque
data:
  DB_PASS: bXlzcWxfc2VuaGE=              # base64 de "mysql_senha"
  ACCESS_TOKEN_SECRET: c2VjcmV0X2FjY2Vzcw==     # base64 de "secret_access"
  REFRESH_TOKEN_SECRET: cmVmcmVzaF9zZWNyZXQ=    # base64 de "refresh_secret"
