apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: lanchonete-app
  labels:
    app: app
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
