apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: lanchonete-app
  labels:
    app: app
spec:
  selector:
    service: app
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
