name: Add RBAC for juclops-tech

on:
  workflow_dispatch: # Executa manualmente

jobs:
  grant-access:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLUSTER_NAME: eks-lanchonete

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          yq --version

      - name: Configurar credenciais AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configurar acesso ao cluster EKS
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME

      - name: Adicionar juclops-tech ao aws-auth
        run: |
          kubectl patch configmap aws-auth -n kube-system \
            --type merge \
            -p '{"data":{"mapUsers":"- userarn: arn:aws:iam::043309328721:user/juclops-tech\n  username: juclops-tech\n  groups:\n    - system:masters"}}'

