name: EKS Infra Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'eks-cluster/**'

jobs:
  terraform-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLUSTER_NAME: eks-lanchonete

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init (infra)
        working-directory: eks-cluster
        run: terraform init

      - name: Terraform Apply (infra)
        working-directory: eks-cluster
        run: terraform apply -auto-approve
