name: Terraform Infra + Kubernetes Deploy

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials via OIDC (assume role)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply (create cluster + infra)
        id: apply_infra
        run: terraform apply -auto-approve

      - name: Get Cluster Name
        id: get_output
        run: |
          echo "cluster_name=$(terraform output -raw eks_cluster_name)" >> $GITHUB_OUTPUT

      - name: Generate kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name ${{ steps.get_output.outputs.cluster_name }}

      - name: Terraform Apply (k8s manifests)
        run: terraform apply -auto-approve
