name: Terraform Deploy to EKS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Apply Terraform on EKS
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      CLUSTER_NAME: tech_challenge
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials via OIDC (assume role)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Generate kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name  ${{ env.CLUSTER_NAME }}
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
