name: Terraform Infra + Kubernetes Deploy

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLUSTER_NAME: eks-lanchonete

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials via OIDC (assume role)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      # =======================
      # EKS INFRASTRUCTURE APPLY
      # =======================
      - name: Terraform Init (infra)
        working-directory: eks-cluster
        run: terraform init

      - name: Terraform Apply (infra)
        working-directory: eks-cluster
        run: terraform apply -auto-approve

      # =======================
      # KUBECONFIG
      # =======================
      - name: Generate kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.CLUSTER_NAME }}

      # =======================
      # APPLY MANIFESTS COM KUBECTL PROVIDER
      # =======================
      - name: Terraform Init (YAML kubectl apply)
        working-directory: .
        run: terraform init

      - name: Terraform Apply (YAML kubectl apply)
        working-directory: .
        run: terraform apply -auto-approve
